from .feature_synonim import get_features_synonim
from .feature_number_exclamation import get_features_number_exclamation
from .feature_mean_len_word import get_features_mean_len_word
from .feature_meta import get_features_meta
from .feature_caps_words import feature_caps_words
from .feature_contradistinctive_particles import feature_contradistinctive_particles
from .feature_firstperson import feature_firstperson
from .feature_length_of_review import feature_length_of_review
from .feature_parts_of_speech import feature_parts_of_speech
#from .feature_shop_answer import get_features_shop_answer
from .feature_unigrams_bigrams import feature_unigrams_bigrams

